---
- name: Web Server Setup
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Install pip for Python 3
      become: yes
      yum:
        name: python3-pip
        state: present

    - name: Install required Python module 'passlib'
      become: yes
      pip:
        name: passlib
        executable: pip3  # Use pip3 as the executable name
        state: present

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - php
        - php-common
        - php-pecl-apcu
        - php-cli
        - php-mysqlnd
      when: ansible_memtotal_mb > 1024

    - name: Create virtual hosts
      template:
        src: vhost.conf.j2
        dest: "/etc/httpd/conf.d/{{ item.name }}.conf"
      with_items:
        - name: ahmed.com
          document_root: "/var/www/html/ahmed.com"
          username: ahmed
          password: 123
        - name: mohamed.com
          document_root: "/var/www/html/mohamed.com"
          username: mohamed
          password: 456

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create htpasswd file for authentication
      htpasswd:
        path: "/etc/httpd/.htpasswd"
        name: "{{ item.username }}"
        password: "{{ item.password }}"
      with_items:
        - { username: 'ahmed', password: '123' }
        - { username: 'mohamed', password: '456' }
    - name: insert ip to hosts
      lineinfile:
        path: /etc/hosts
        line: "192.168.43.145  ahmed.com"
        state: present
      when: inventory_hostname=='httpd_1'
    - name: configure web ahmed
      copy:
        src: ahmed.html
        dest: /var/www/html/ahmed.com/index.html
      notify:
        - restart httpd

  handlers:
    - name: restart httpd
      service:
       name: httpd
       state: restarted
